export const ADD_EXIST_ING = 'ADD_EXIST_ING';
export const REMOVE_EXIST_ING = 'REMOVE_EXIST_ING';
export const INIT_RECEPIES_BY_INGREDIENTS = 'INIT_RECEPIES_BY_INGREDIENTS';
export const INIT_RECEPIES_BY_NUTRIENTS = 'INIT_RECEPIES_BY_NUTRIENTS';
export const UPDATE_NUTRIENTS_VALUE = 'UPDATE_NUTRIENTS_VALUE'